<script lang="ts">
  import Tech from "$lib/components/tech.svelte";

  const techs = [
    { name: "SvelteKit", href: "https://kit.svelte.dev" },
    { name: "tRPC", href: "https://trpc.io" },
    { name: "TypeScript", href: "https://typescriptlang.org" },
  ];
</script>

<svelte:head>
  <title>Create SKT3 App</title>
  <meta name="description" content="Generated by create-skt3-app" />
  <link rel="icon" href="/favicon.ico" />
</svelte:head>

<div>
  <h1>
    Create <span>SKT3</span> App
  </h1>

  <div>
    <h3>This stack uses:</h3>
    <ul>
      {#each techs as { name, href }}
        <Tech {name} {href} />
      {/each}
    </ul>
  </div>
</div>
